#' @param tree A tree of class \code{\link[ape]{phylo}}, with tip labels in the order generated by 
#'             \code{\link{RenumberTips}}, i.e. corresponding to the sequence of taxa 
#'             in the corresponding Morphy object. 
