---
title: "Computing clade movement"
author: "[Martin R. Smith](https://smithlabdurham.github.io/)"
output: rmarkdown::html_vignette
bibliography: ../inst/REFERENCES.bib
csl: ../inst/apa-old-doi-prefix.csl
vignette: >
  %\VignetteIndexEntry{Computing clade movement}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Concept

This is a method for considering the change in position of a specified clade
between two rooted, weighted trees.
The method can also be applied to unweighted trees by assigning each edge
a unit length, though this may place undue weight on changes in tree shape.

The method takes inspiration the concept of "concestors" [@Dawkins2004]:
successive common ancestors of a focal clade and its increasingly distant
relatives.
A tree implies an evolutionary history for each clade, whose earlier reaches
will be held in common with an increasingly broad sample of other leaves.
If a clade occurs in different positions in two trees, it will share its
evolutionary history with a different set of taxa.

Put simply, if a clade is in the "same place" in two trees, then it will have 
the same sequence of concestors;
if it moves rootward, its will share less of its ancestry with close relatives;
if it is in a different part in the tree its ancestors will be different.

Put another way, the edges of a tree can be interpreted as periods of time in
which evolutionary events (mutations / innovations) are added to the
evolutionary history of all descendant taxa.
The position of a clade can be described in terms of the number of events it
holds in common with other taxa.

## Application

This concept is relatively simple to apply to leaves of a tree.

```{r two-trees-leaves}
library("TreeTools")
tree1 <- ape::read.tree(text = "(1:1, (2:1, (3:1, (4:1, (5:1, 6:1):1):1):1):2);")
tree2 <- ape::read.tree(text = "(1:1, (4:1, (2:1, (3:1, (5:1, 6:1):2):1):1):1);")

Heritage(tree1)
Heritage(tree2)

tipMotion <- colSums(TipMotion(tree1, tree2))
maxMotion <- max(tipMotion)

# Configure plotting area
oPar <- par(mfrow = c(1, 2), mar = rep(0.1, 4))

# Plot trees
plot(tree1)
tiplabels(bg = hcl.colors(maxMotion + 1)[tipMotion + 1])
plot(tree2)
tiplabels(bg = hcl.colors(maxMotion + 1)[tipMotion + 1])
# Add legend
PlotTools::SpectrumLegend(
  "bottomleft",
  palette = hcl.colors(maxMotion + 1),
  title = "Tip Motion",
  legend = round(seq(maxMotion, 0, len = 4), 1),
  bty = "n"
)
```
