#' Thirty Datasets with Inapplicable data
#' 
#' These are the datasets used to evaluate the behaviour of the inapplicable algorithm 
#' in Brazeau, Guillerme and Smith (2017).
#'
#' The name of each item corresponds to the datasets listed below.
#' Datasets are sorted into two subsets, each sorted alphabetically;
#' the first subset comprise simpler datasets with faster processing times.
#' The value is the dataset in the format generated by \code{\link{read.nexus.data}}.
#'
#' @keywords datasets
#' @template inapplicableSources
#'
#' @template studyReference
"inapplicable.datasets"

#' Thirty Datasets with Inapplicable data
#' 
#' These are the datasets used to evaluate the behaviour of the inapplicable algorithm 
#' in Brazeau, Guillerme and Smith (2017).
#'
#' The name of each item corresponds to the datasets listed below.
#' Datasets are sorted into two subsets, each sorted alphabetically;
#' the first subset comprise simpler datasets with faster processing times.
#' The value is the dataset in \code{phyDat} format.
#'
#' @template inapplicableSources
#'
#' @template studyReference
#'
#' @keywords datasets
"inapplicable.phyData"

#' Thirty Datasets with Inapplicable data
#' 
#' These are the datasets used to evaluate the behaviour of the inapplicable algorithm 
#' in Brazeau, Guillerme and Smith (2017).
#'
#' The name of each item corresponds to the datasets listed below.  The value gives its citation.
#'
#' @template inapplicableSources
#'
#' @template studyReference
#'
#' @keywords datasets
"inapplicable.citations"


#' Raw data from Zhang et al. 2016
#'
#' @template LoboMods
#'
#' @keywords datasets
#' @source Zhang X-G, Smith MR, Yang J, Hou J-B. 2016 Onychophoran-like musculature in a phosphatized Cambrian lobopodian. Biol. Lett. 12: 20160492. \url{http://dx.doi.org/10.1098/rsbl.2016.0492}
"Lobo.data"

#' Data from Zhang et al. 2016 in phyDat format
#'
#' @template LoboMods
#'
#' @keywords datasets
#' @source Zhang X-G, Smith MR, Yang J, Hou J-B. 2016 Onychophoran-like musculature in a phosphatized Cambrian lobopodian. Biol. Lett. 12: 20160492. \url{http://dx.doi.org/10.1098/rsbl.2016.0492}
"Lobo.phy"

