#' Information-based generalized Robinson-Foulds distances between two trees.
#'
#' Tree similarity and distance measures that measure the amount of 
#' phylogenetic or clustering information that two trees hold in common.
#' 
#' 
#' A tree similarity measure is generated by finding an optimal matching that
#' maximises the total information in common between a partition on one tree
#' and its pair on a second, considering all possible ways to pair partitions 
#' between trees (including leaving a partition unpaired).
#' 
#' The returned tree similarity measures state the amount of information, 
#' in bits, that the partitions in two trees hold in common 
#' when they are optimally matched, following Smith (forthcoming).  
#' The complementary tree distance measures state how much information is 
#' different in the partitions of two trees, under an optimal matching.
#' 
#' @section Concepts of information:
#'
#' Each partition in a tree can be viewed as a statement that the 'true' 
#' tree is one of those that splits the taxa as specified.  This concept
#' corresponds to the concept of phylogenetic information, which views the
#' information content of a pair of partitions as relating to the proportion of
#' phylogenetic trees that are consistent with both partitions.
#' 
#' This proportion gives rise to the Mutual Phylogenetic Information similarity 
#' measure (`MutualPhylogeneticInfo`), and the complementary 
#' Variation of Phylogenetic Information distance metric
#' (`VariationOfPhylogeneticInfo`).
#' 
#' An information-theoretic take on the [`MatchingSplitDistance`] offers a 
#' relaxed interpretation of this measurement, which attributes some information
#' to similar yet contradictory splits.  This metric exhibits undesirable
#' properties, but is implemented in `MutualMatchingSplitInfo` and 
#' `VariationOfMatchingSplitInfo`.
#' 
#' Alternatively, each partition can be viewed as a statement that the taxa
#' are subdivided into the two groups specified.  On this view, the 
#' information content of a pair of partitions corresponds to their
#' mutual clustering information (Meila 2007, Vinh2010), giving rise to their
#' Mutucal Clustering Information and Variation of Clustering Information
#' similarity/distance metrics (`MutualClusteringInfo`, `VariationOfClusteringInfo`)
#' 
#' 
#' @section Normalization:
#' 
#' If `normalize = TRUE`, then results will be rescaled from zero to a nominal
#' maximum value, calculated thus:
#' 
#' * `MutualPhylogeneticInfo`, `MutualClusteringInfo`, `MutualMatchingSplitInfo`:
#'  The information content of the least informative tree.
#'  To scale against the information content of the most informative tree, use
#' `normalize = pmax`.
#' 
#' * `VariationOfPhylogeneticInfo`, `VariationOfClusteringInfo`,
#' `VariationOfMatchingSplitInfo`: The sum of the
#' (phylogenetic or clustering) information content of the two trees.
#' 
#' @template tree12Params
#' 
#' @param normalize If a numeric value is provided, this will be used as a 
#' maximum value against which to rescale results.
#' If `TRUE`, results will be rescaled against a maximum value calculated from
#' the specified tree sizes and topology, as specified in the 'Normalization' 
#' section below.
#' If `FALSE`, results will not be rescaled.
#' 
#' @param reportMatching Logical specifying whether to return the clade
#' matchings as an attribute of the score.
#'
#' @return If `reportMatching = FALSE`, the functions return a numeric 
#' vector specifying the requested similarities or differences.
#' 
#' If `reportMatching = TRUE`, the functions additionally return details
#' of which clades are matched in the optimal matching, which can be viewed
#' using [`VisualizeMatching`].
#'  
#' @examples {
#'   tree1 <- ape::read.tree(text='((((a, b), c), d), (e, (f, (g, h))));')
#'   tree2 <- ape::read.tree(text='(((a, b), (c, d)), ((e, f), (g, h)));')
#'   tree3 <- ape::read.tree(text='((((h, b), c), d), (e, (f, (g, a))));')
#'   
#'   # Best possible score is obtained by matching a tree with itself
#'   VariationOfPhylogeneticInfo(tree1, tree1) # 0, by definition
#'   MutualPhylogeneticInfo(tree1, tree1)
#'   PartitionInfo(tree1) # Maximum mutual phylogenetic information
#'   
#'   # Best possible score is a function of tree shape; the partitions within
#'   # balanced trees are more independent and thus contain less information
#'   PartitionInfo(tree2)
#'   
#'   # How similar are two trees?
#'   MutualPhylogeneticInfo(tree1, tree2) # Amount of phylogenetic information in common
#'   VisualizeMatching(MutualPhylogeneticInfo, tree1, tree2) # Which clades are matched?
#'   VariationOfPhylogeneticInfo(tree1, tree2) # Distance measure
#'   VariationOfPhylogeneticInfo(tree2, tree1) # The metric is symmetric
#'   #'   
#'   # Are they more similar than two trees of this shape would be by chance?
#'   ExpectedVariation(tree1, tree2, sample=12)['VariationOfPhylogeneticInfo', 'Estimate']
#'   
#'   # Every partition in tree1 is contradicted by every partition in tree3
#'   # Non-arboreal matches contain clustering, but not phylogenetic, information
#'   MutualPhylogeneticInfo(tree1, tree3) # = 0
#'   MutualClusteringInfo(tree1, tree3) # > 0
#'   
#' }
#' 
#' 
#' @references {
#'  * \insertRef{Meila2007}{TreeDist}
#'  * \insertRef{SmithDist}{TreeDist}
#'  * \insertRef{Vinh2010}{TreeDist}
#' }
#' 
#' @author Martin R. Smith
#' 
#' @family tree distances
#' @importFrom clue solve_LSAP
#' @export
MutualPhylogeneticInfo <- function (tree1, tree2, normalize = FALSE,
                                reportMatching = FALSE) {
  unnormalized <- CalculateTreeDistance(MutualPhylogeneticInfoSplits, tree1, tree2, 
                                        reportMatching=reportMatching)
  
  # Return:
  NormalizeInfo(unnormalized, tree1, tree2, how = normalize,
                InfoInTree = PartitionInfo, Combine = pmin)
}

#' @describeIn MutualPhylogeneticInfo Variation of phylogenetic information between two trees.
#' @export
VariationOfPhylogeneticInfo <- function (tree1, tree2, normalize = FALSE,
                                     reportMatching = FALSE) {
  mai <- MutualPhylogeneticInfo(tree1, tree2, normalize = FALSE,
                            reportMatching = reportMatching)
  treesIndependentInfo <- outer(PartitionInfo(tree1), PartitionInfo(tree2), '+')
  
  ret <- treesIndependentInfo - mai - mai
  ret <- NormalizeInfo(ret, tree1, tree2, how=normalize, 
                       infoInBoth = treesIndependentInfo,
                       InfoInTree = PartitionInfo, Combine = '+')
  
  ret[ret < 1e-13] <- 0 # In case of floating point inaccuracy
  attributes(ret) <- attributes(mai)
  
  # Return:
  ret
}

#' @describeIn MutualPhylogeneticInfo Variation of clustering information between two trees.
#' @export
VariationOfClusteringInfo <- function (tree1, tree2, normalize = FALSE,
                                       reportMatching = FALSE) {
  mci <- MutualClusteringInfo(tree1, tree2, normalize = FALSE, 
                              reportMatching = reportMatching)
  treesIndependentInfo <- outer(ClusteringInfo(tree1), ClusteringInfo(tree2), '+')
  
  ret <- treesIndependentInfo - mci - mci
  ret <- NormalizeInfo(ret, tree1, tree2, how = normalize,
                       infoInBoth = treesIndependentInfo,
                       InfoInTree = ClusteringInfo, Combine = '+')
  
  ret[ret < 1e-13] <- 0 # In case of floating point inaccuracy
  attributes(ret) <- attributes(mci)
  
  # Return:
  ret
}

#' @describeIn MutualPhylogeneticInfo Estimate expected Variation of 
#' Phylogenetic Information and Mutual Phylogenetic Information for a pair of trees of
#' a given topology.
#' @param samples Integer specifying how many samplings to obtain; 
#' accuracy of estimate increases with `sqrt(samples)`.
#' @importFrom stats sd
#' @importFrom TreeSearch Tree2Splits
#' @export
ExpectedVariation <- function (tree1, tree2, samples = 1e+3) {
  info1 <- PartitionInfo(tree1)
  info2 <- PartitionInfo(tree2)
  splits1 <- Tree2Splits(tree1)
  splits2 <- Tree2Splits(tree2)
  tipLabels <- rownames(splits2)
  
  mutualEstimates <- vapply(seq_len(samples), function (x) {
    rownames(splits2) <- sample(tipLabels)
    c(MutualPhylogeneticInfoSplits(splits1, splits2),
      MutualMatchingSplitInfoSplits(splits1, splits2))
  }, c(MutualPhylogeneticInfo = 0, MutualMatchingSplitInfo = 0))
  
  mut <- cbind(Estimate = rowMeans(mutualEstimates),
               sd = apply(mutualEstimates, 1, sd), n = samples)
  
  ret <- rbind(mut,
               VariationOfPhylogeneticInfo = c(info1 + info2 - mut[1, 1] - mut[1, 1], mut[1, 2] * 2, samples),
               VariationOfMatchingSplitInfo =  c(info1 + info2 - mut[2, 1] - mut[2, 1], mut[2, 2] * 2, samples)
               )
  
  # Return:
  cbind(Estimate = ret[, 1], 'Std. Err.' = ret[, 'sd'] / sqrt(ret[, 'n']), ret[, 2:3])
}

#' @describeIn MutualPhylogeneticInfo Mutual Clustering Information of two trees.
#' @export
MutualClusteringInfo <- function (tree1, tree2, normalize = FALSE,
                                  reportMatching = FALSE) {
  unnormalized <- CalculateTreeDistance(MutualClusteringInfoSplits, tree1, tree2,
                                        reportMatching)
  NormalizeInfo(unnormalized, tree1, tree2, ClusteringInfo, 
                how = normalize, Combine = pmin)
}

#' @describeIn MutualPhylogeneticInfo Calculate mutual phylogenetic information from splits instead of trees.
#' @template splits12params
#' @export
MutualPhylogeneticInfoSplits <- function (splits1, splits2, normalize = TRUE,
                                      reportMatching = FALSE) {
  
  dimSplits1 <- dim(splits1)
  dimSplits2 <- dim(splits2)
  nTerminals <- dimSplits1[1]
  if (dimSplits2[1] != nTerminals) {
    stop("Split rows must bear identical labels")
  }
  lnUnrootedN <- LnUnrooted.int(nTerminals)
  
  swapSplits <- (dimSplits1[2] > dimSplits2[2])
  if (swapSplits) {
    # solve_LDAP expects splits1 to be no larger than splits2
    tmp <- splits1
    splits1 <- splits2
    splits2 <- tmp
    
    tmp <- dimSplits1
    dimSplits1 <- dimSplits2
    dimSplits2 <- tmp
  }
  
  taxonNames1 <- rownames(splits1)
  taxonNames2 <- rownames(splits2)
  
  if (!is.null(taxonNames2)) {
    splits2 <- unname(splits2[taxonNames1, , drop=FALSE])
    splits1 <- unname(splits1) # split2[split1] faster without names
  }
  
  nSplits1 <- dimSplits1[2]
  nSplits2 <- dimSplits2[2]
  if (nSplits1 == 0) return (0)
  inSplit1 <- colSums(splits1)
  inSplit2 <- colSums(splits2)
  notInSplit2 <- nTerminals - inSplit2
  
  if (nTerminals <= length(oneOverlap)) {
    # Use cache for speed, if available
    oo <- oneOverlap[[nTerminals]]
    OneOverlap <- function (A1, A2) oo[A1, A2]
  } else {
    OneOverlap <- function(A1, A2) {
      if (A1 == A2) {
        # Return:
        LnRooted.int(A1) + LnRooted.int(nTerminals - A2)
      } else {
        if (A1 < A2) {
          # Return:
          LnRooted.int(A2) + LnRooted.int(nTerminals - A1) - LnRooted.int(A2 - A1 + 1L) 
        } else {
          # Return:
          LnRooted.int(A1) + LnRooted.int(nTerminals - A2) - LnRooted.int(A1 - A2 + 1L) 
        }
      }
    }
  }
  
  pairScores <- matrix((mapply(function(i, j) {
    split1 <- splits1[, i]
    split2 <- splits2[, j]
    
    if (all(split1[split2]) || # oneAndTwo
        all(!split1[!split2])) { # notOneNotTwo
      OneOverlap(inSplit1[i], inSplit2[j])
      
    } else if (all(!split1[split2]) || # notOneAndTwo
               all(split1[!split2])) { #oneNotTwo
      OneOverlap(inSplit1[i], notInSplit2[j])
      
    } else {
      lnUnrootedN
    }
  }, seq_len(nSplits1), rep(seq_len(nSplits2), each=nSplits1)
  ) - lnUnrootedN) / -log(2), nSplits1, nSplits2)
  
  if (nSplits1 == 1) {
    max(pairScores)
  } else {
    optimalMatching <- solve_LSAP(pairScores, TRUE)

    # Return:
    ret <- sum(pairScores[matrix(c(seq_along(optimalMatching), optimalMatching), ncol=2L)])
    if (reportMatching) {
      if (!is.null(taxonNames2)) {
        attr(ret, 'matchedSplits') <- 
        if (swapSplits) {
          ReportMatching(splits2[, optimalMatching], splits1, taxonNames1)
        } else {
          ReportMatching(splits1, splits2[, optimalMatching], taxonNames1)
        }
      }
      attr(ret, 'matching') <- optimalMatching
      attr(ret, 'pairScores') <- pairScores
      ret
    } else {
      ret
    }
  }
}

#' @describeIn MutualPhylogeneticInfo Calculate variation of matching split information from splits instead of trees.
#' @inheritParams MutualPhylogeneticInfoSplits
#' @importFrom TreeSearch LnUnrooted.int LogTreesMatchingSplit
#' @export
MutualMatchingSplitInfoSplits <- function (splits1, splits2, reportMatching = FALSE) {
  dimSplits1 <- dim(splits1)
  dimSplits2 <- dim(splits2)
  nTerminals <- dimSplits1[1]
  if (dimSplits2[1] != nTerminals) {
    stop("Split rows must bear identical labels")
  }
  
  swapSplits <- (dimSplits1[2] > dimSplits2[2])
  if (swapSplits) {
    # solve_LDAP expects splits1 to be no larger than splits2
    tmp <- splits1
    splits1 <- splits2
    splits2 <- tmp
    
    tmp <- dimSplits1
    dimSplits1 <- dimSplits2
    dimSplits2 <- tmp
    
    remove(tmp)
  }
  
  taxonNames1 <- rownames(splits1)
  taxonNames2 <- rownames(splits2)
  
  if (!is.null(taxonNames2)) {
    splits2 <- unname(splits2[taxonNames1, , drop=FALSE])
    splits1 <- unname(splits1) # split2[split1] faster without names
  }
  
  nSplits1 <- dimSplits1[2]
  nSplits2 <- dimSplits2[2]
  if (nSplits1 == 0) return (0)
  
  AgreementInfoNats <- function (splitI, agree) {
    inAgreement <- sum(agree)
    n0 <- sum(splitI[agree])
    LnUnrooted.int(inAgreement) - LogTreesMatchingSplit(n0, inAgreement - n0)
  }
  
  pairScores <- matrix((mapply(function(i, j) {
    splitI0 <- splits1[, i]
    splitJ0 <- splits2[, j]
    
    agree1 <- splitI0 == splitJ0
    
    max(AgreementInfoNats(splitI0, agree1),
        AgreementInfoNats(splitI0, !agree1))
    
  }, seq_len(nSplits1), rep(seq_len(nSplits2), each=nSplits1)
  )), nSplits1, nSplits2) / log(2)
  
  if (nSplits1 == 1) {
    min(pairScores)
  } else {
    optimalMatching <- solve_LSAP(pairScores, TRUE)
    
    # Return:
    ret <- sum(pairScores[matrix(c(seq_along(optimalMatching), optimalMatching), ncol=2L)])
    if (reportMatching) {
      if (!is.null(taxonNames2)) {
        attr(ret, 'matchedSplits') <- 
          if (swapSplits) {
            ReportMatching(splits2[, optimalMatching], splits1, taxonNames1)
          } else {
            ReportMatching(splits1, splits2[, optimalMatching], taxonNames1)
          }
      }
      attr(ret, 'matching') <- optimalMatching
      attr(ret, 'pairScores') <- pairScores
      ret
    } else {
      ret
    }
  }
}

#' @describeIn MutualPhylogeneticInfo Calculate clustering information from splits instead of trees
#' @export
MutualClusteringInfoSplits <- function (splits1, splits2, normalize = TRUE,
                                        reportMatching = FALSE) {
  
  dimSplits1 <- dim(splits1)
  dimSplits2 <- dim(splits2)
  nTerminals <- dimSplits1[1]
  if (dimSplits2[1] != nTerminals) {
    stop("Split rows must bear identical labels")
  }
  
  swapSplits <- (dimSplits1[2] > dimSplits2[2])
  if (swapSplits) {
    # solve_LDAP expects splits1 to be no larger than splits2
    tmp <- splits1
    splits1 <- splits2
    splits2 <- tmp
    
    tmp <- dimSplits1
    dimSplits1 <- dimSplits2
    dimSplits2 <- tmp
    
    remove(tmp)
  }
  
  taxonNames1 <- rownames(splits1)
  taxonNames2 <- rownames(splits2)
  
  if (!is.null(taxonNames2)) {
    splits2 <- unname(splits2[taxonNames1, , drop=FALSE])
    splits1 <- unname(splits1) # split2[split1] faster without names
  }
  
  nSplits1 <- dimSplits1[2]
  nSplits2 <- dimSplits2[2]
  if (nSplits1 == 0) return (0)
  
  
  pairScores <- matrix((mapply(function(i, j) {
    MeilaMutualInformation(splits1[, i], splits2[, j])
  }, seq_len(nSplits1), rep(seq_len(nSplits2), each=nSplits1)
  )), nSplits1, nSplits2) / log(2)
  
  if (nSplits1 == 1) {
    min(pairScores)
  } else {
    optimalMatching <- solve_LSAP(pairScores, TRUE)
    
    # Return:
    ret <- sum(pairScores[matrix(c(seq_along(optimalMatching), optimalMatching), ncol=2L)])
    if (reportMatching) {
      if (!is.null(taxonNames2)) {
        attr(ret, 'matchedSplits') <- 
          if (swapSplits) {
            ReportMatching(splits2[, optimalMatching], splits1, taxonNames1)
          } else {
            ReportMatching(splits1, splits2[, optimalMatching], taxonNames1)
          }
      }
      attr(ret, 'matching') <- optimalMatching
      attr(ret, 'pairScores') <- pairScores
      ret
    } else {
      ret
    }
  }
}

#' Are splits compatible?
#' 
#' Splits are compatible if they are concave; i.e. they can both be true
#' simultaneously.
#' 
#' @template split12Params
#' @return `SplitsCompatible` returns a logical specifying whether the splits
#' provided are compatible with one another.
#' 
#' @author Martin R. Smith
#' @export
SplitsCompatible <- function (split1, split2) {
  # Return:
  (
    all (split1[split2]) ||
    all(split1[!split2]) ||
    all(!split1[split2]) ||
    all(!split1[!split2])
  )
}
