name: Benchmark

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yaml"
      - "**.yml"
      - "!**benchmark.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"

jobs:
  benchmark_pr:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/noble/latest"
      _R_CHECK_BUILD_VIGNETTES_: false
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_FORCE_SUGGESTS_: false # CRAN settings
      R_REMOTES_STANDALONE: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_REALLY_FORCE_SYMBOLS: true # Until R4.3
      R_COMPILE_OPT: "3"
      
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: https://ms609.github.io/packages/
        
      - name: Install packages
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_github("ms609/TreeTools", ref = "benchmarking")'
          
      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          needs: benchmark
        
      - name: Install package
        run: R CMD INSTALL . --preclean --clean --byte-compile --no-docs --no-help --no-test-load --no-multiarch

      - name: Run benchmarks for PR
        run: Rscript benchmark/_run_benchmarks.R
        shell: bash

      - name: Upload PR benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: pr-benchmark-results
          path: '*.bench.Rds'

  benchmark_main:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/noble/latest"
      R_COMPILE_OPT: "3"
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: https://ms609.github.io/packages/

      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          needs: benchmark

      - name: Install package
        run: R CMD INSTALL . --preclean --clean --byte-compile --no-docs --no-help --no-test-load --no-multiarch
        
      - name: Run benchmarks for main branch
        run: Rscript benchmark/_run_benchmarks.R
        shell: bash

      - name: Upload main benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: main-benchmark-results
          path: '*.bench.Rds'

  compare_benchmarks:
    runs-on: ubuntu-latest
    needs: [benchmark_pr, benchmark_main]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          Rscript -e 'install.packages("microbenchmark")'

      - name: Download PR benchmark results
        uses: actions/download-artifact@v4
        with:
          name: pr-benchmark-results
          path: pr-benchmark-results

      - name: Download main benchmark results
        uses: actions/download-artifact@v4
        with:
          name: main-benchmark-results
          path: main-benchmark-results

      - name: Compare benchmarks and comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          Rscript benchmark/_compare_results.R
        shell: bash
