name: Benchmark

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "Meta**"
      - "memcheck**"
      - "docs**"
      - "**.git"
      - "**.json"
      - "**.md"
      - "**.yaml"
      - "**.yml"
      - "!**benchmark.yml"
      - "**.R[dD]ata"
      - "**.Rpro*"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/noble/latest"
      _R_CHECK_BUILD_VIGNETTES_: false
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_FORCE_SUGGESTS_: false # CRAN settings
      R_REMOTES_STANDALONE: true
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_REALLY_FORCE_SYMBOLS: true # Until R4.3
      
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          path: pr
          
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref || 'master' }}
          path: main

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: https://ms609.github.io/packages/
        
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            remotes
            github::ms609/TreeTools
          dependencies: '"hard"'
          needs: benchmark

      - name: Benchmark PR
        working-directory: pr
        run: |
          R CMD INSTALL . --preclean --clean --byte-compile --no-docs --no-help --no-test-load --no-multiarch
          Rscript benchmark/_run_benchmarks.R
          mkdir ./pr-benchmark-results/
          mv *.bench.Rds ./pr-benchmark-results/
        shell: bash
        
      - name: Benchmark main
        working-directory: main
        run: |
          Rscript -e 'install.packages("TreeTools")'
          R CMD INSTALL . --preclean --clean --byte-compile --no-docs --no-help --no-test-load --no-multiarch
          Rscript benchmark/_run_benchmarks.R
          mkdir ../pr/main-benchmark-results/
          mv *.bench.Rds ../pr/main-benchmark-results/
        shell: bash
        
      - name: Benchmark PR
        working-directory: pr
        run: |
          Rscript -e 'remotes::install_github("ms609/TreeTools")'
          R CMD INSTALL . --preclean --clean --byte-compile --no-docs --no-help --no-test-load --no-multiarch
          Rscript benchmark/_run_benchmarks.R
          mkdir ./pr2-benchmark-results/
          mv *.bench.Rds ./pr2-benchmark-results/
        shell: bash

      - run: dir pr-benchmark-results
        working-directory: pr
      - run: dir main-benchmark-results
        working-directory: pr

      - name: Compare benchmarks
        id: compare_results
        working-directory: pr
        run: |
          Rscript benchmark/_compare_results.R
        shell: bash
        
      - name: Comment on PR
        if: always() && github.event_name == 'pull_request' && steps.compare_results.outputs.report != ''
        uses: actions/github-script@v7
        env:
          BENCHMARK_MESSAGE: ${{ steps.compare_results.outputs.report }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: process.env.BENCHMARK_MESSAGE
            });
